name: 'Build war file on PR'

on:
  pull_request:
    branches: [main]
    paths-ignore:
    - "**.md"
    - "*.txt"
    - ".github/**" 
    - "!.github/workflows/pr_build_war.yml"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == github.event.pull_request.head.repo.full_name
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        java-version: 21
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn package -DskipTests -B -P docker
    - name: Upload war file
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: airsonic-advanced
        path: airsonic-main/target/airsonic.war
        retention-days: 30
        overwrite: true
    