name: 'Build docker image on PR'

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "*.txt"
      - ".github/**" 
      - "!.github/workflows/pr_build_docker.yml"
  pull_request_target:
    types: 
      - labeled


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      github.repository == github.event.pull_request.head.repo.full_name || 
      (github.repository != github.event.pull_request.head.repo.full_name && contains(github.event.pull_request.labels.*.name, 'safe to test'))
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build with Maven
        run: mvn package -DskipTests -B -P integration-test
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images to GHCR
        uses: docker/build-push-action@v4
        with:
          file: install/docker/Dockerfile
          context: install/docker
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/kagemomiji/airsonic-advanced:pr-${{ github.event.pull_request.number }}
