name: Trivy scan
on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'


jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.9.1
        with:
          scan-type: 'fs'
          format: 'sarif'
          ignore-unfixed: true
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'